spring.application.name=EvolutionERP
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=evo
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/evolution_erp
spring.datasource.username=postgres
spring.datasource.password=postgre
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=public,evo
spring.flyway.baselineOnMigrate=true
spring.flyway.baselineVersion=0
jwt.secret=NMVz2aolBAj5h1pBi9614WS2aBbG2kFiiK/iSZkzRi1mkfenvDzLKwR3YP9PzaeIFl0EDJOz1AtuCBjat2yMkw==
jwt.expiration=18000000
server.port=8085
spring.jackson.date-format=dd/MM/yyyy HH:mm:ss
spring.jackson.time-zone=America/Lima
